Template the xcaddy download
Signed-off-by: Dave Henderson <dhenderson@gmail.com>

diff --git a/2.1/builder/Dockerfile b/2.1/builder/Dockerfile
--- a/2.1/builder/Dockerfile
+++ b/2.1/builder/Dockerfile
@@ -1,19 +1,32 @@
-FROM golang:1.14-alpine3.12 AS builder
-
-WORKDIR /src
+FROM golang:1.14-alpine3.12
 
 RUN apk add --no-cache \
     git \
     ca-certificates
 
-ENV CADDY_SOURCE_VERSION=v2.1.1
+ENV XCADDY_VERSION v0.1.5
+# Configures xcaddy to build with this version of Caddy
+ENV CADDY_VERSION v2.1.1
+# Configures xcaddy to not clean up post-build (unnecessary in a container)
+ENV XCADDY_SKIP_CLEANUP 1
 
-RUN git clone -b $CADDY_SOURCE_VERSION https://github.com/caddyserver/caddy.git --single-branch
-
-WORKDIR /src/caddy/cmd/caddy
-
-RUN go get -d ./...
+RUN set -eux; \
+	apkArch="$(apk --print-arch)"; \
+	case "$apkArch" in \
+		x86_64)  binArch='amd64'; checksum='3d71e90a4b4f3ebc55d79086d5fb4e36d675fd067435b0a2e37f50361e89ceb58a4b8eae43ea502d1b6d1522c3020f1791ffad9a9fbd374883c6202cf9ed67f7' ;; \
+		armhf)   binArch='armv6'; checksum='243f58f32bba0b6295267ba78ed18c1b36dfd3c8af4ddbe1f8e1fe096a58cb3326d795b19ce06d87b8641fc17d6e8f1fd2ee372af7dca8c844544768cd05c418' ;; \
+		armv7)   binArch='armv7'; checksum='51c212b44bf21e3d9feb841cb91c93289f5244d7276a7ce4b1eea73121855345190de77f4a87a3e4e1a93cccf6085133b8552de48687c2164277c0766d3404f0' ;; \
+		aarch64) binArch='arm64'; checksum='13c3184699c20734a5718cad3e4ee8fed52df1eca21d0d3fa5d34a671990bfd1fae23824c7618c0cba1ceac6262b3225f85cbb37cd9c162935c2c367c623e1ea' ;; \
+		ppc64el|ppc64le) binArch='ppc64le'; checksum='faf068bb6b6086881504699fb92f77f628e36297eda3651021fea40a06a2fa043453a729000d460e530b2772420071b65fdd3915abfdd4d47dbf820e3590393d' ;; \
+		s390x)   binArch='s390x'; checksum='79527340291d9e2196079c87daabe6fed5f5e354dc3a4a37e59c684aeed910376b472e4d8969c3ae957f1af35272d46e669fa111fcb47bb90a0822aa039970ea' ;; \
+		*) echo >&2 "error: unsupported architecture ($apkArch)"; exit 1 ;;\
+	esac; \
+	wget -O /tmp/xcaddy.tar.gz "https://github.com/caddyserver/xcaddy/releases/download/v0.1.5/xcaddy_0.1.5_linux_${binArch}.tar.gz"; \
+	echo "$checksum  /tmp/xcaddy.tar.gz" | sha512sum -c; \
+	tar x -z -f /tmp/xcaddy.tar.gz -C /usr/bin xcaddy; \
+	rm -f /tmp/xcaddy.tar.gz; \
+	chmod +x /usr/bin/xcaddy;
 
 COPY caddy-builder.sh /usr/bin/caddy-builder
 
-WORKDIR /src/custom-caddy/cmd/caddy
+WORKDIR /usr/bin
diff --git a/Dockerfile.builder.tmpl b/Dockerfile.builder.tmpl
--- a/Dockerfile.builder.tmpl
+++ b/Dockerfile.builder.tmpl
@@ -1,19 +1,32 @@
-{{ .base | strings.TrimSpace }} AS builder
-
-WORKDIR /src
+{{ .base | strings.TrimSpace }}
 
 RUN apk add --no-cache \
     git \
     ca-certificates
 
-ENV CADDY_SOURCE_VERSION=v{{ .config.caddy_version }}
+ENV XCADDY_VERSION v{{ .xcaddy_config.version }}
+# Configures xcaddy to build with this version of Caddy
+ENV CADDY_VERSION v{{ .config.caddy_version }}
+# Configures xcaddy to not clean up post-build (unnecessary in a container)
+ENV XCADDY_SKIP_CLEANUP 1
 
-RUN git clone -b $CADDY_SOURCE_VERSION https://github.com/caddyserver/caddy.git --single-branch
-
-WORKDIR /src/caddy/cmd/caddy
-
-RUN go get -d ./...
+RUN set -eux; \
+	apkArch="$(apk --print-arch)"; \
+	case "$apkArch" in \
+		x86_64)  binArch='amd64'; checksum='{{ .xcaddy_config.checksums.amd64 }}' ;; \
+		armhf)   binArch='armv6'; checksum='{{ .xcaddy_config.checksums.arm32v6 }}' ;; \
+		armv7)   binArch='armv7'; checksum='{{ .xcaddy_config.checksums.arm32v7 }}' ;; \
+		aarch64) binArch='arm64'; checksum='{{ .xcaddy_config.checksums.arm64v8 }}' ;; \
+		ppc64el|ppc64le) binArch='ppc64le'; checksum='{{ .xcaddy_config.checksums.ppc64le }}' ;; \
+		s390x)   binArch='s390x'; checksum='{{ .xcaddy_config.checksums.s390x }}' ;; \
+		*) echo >&2 "error: unsupported architecture ($apkArch)"; exit 1 ;;\
+	esac; \
+	wget -O /tmp/xcaddy.tar.gz "https://github.com/caddyserver/xcaddy/releases/download/v{{ .xcaddy_config.version }}/xcaddy_{{ .xcaddy_config.version }}_linux_${binArch}.tar.gz"; \
+	echo "$checksum  /tmp/xcaddy.tar.gz" | sha512sum -c; \
+	tar x -z -f /tmp/xcaddy.tar.gz -C /usr/bin xcaddy; \
+	rm -f /tmp/xcaddy.tar.gz; \
+	chmod +x /usr/bin/xcaddy;
 
 COPY caddy-builder.sh /usr/bin/caddy-builder
 
-WORKDIR /src/custom-caddy/cmd/caddy
+WORKDIR /usr/bin
